### ISSUE TITLE
Bulber closes on start

### ISSUE THREAD

**Issue by funcstar** [buddhi1980/mandelbulber2#609]
Hey there. I love this program but it refuses to work on my computer anymore. I just did a full format for my laptop and still the problem remains. Using the latest build i found.

i got i7  and 16g ram and gtx1070 , win 10 

So when i open the software it closes by itself in a matter of seconds. No error message given so i have no idea whats causing this. Plus im no wizard when it comes to computers. It did work on this same machine a while back but now no matter what i do it just closes. please help.

update there was an error in the box i was able to take a screenshot before it crashed

https://imgur.com/a/eWaSp58

help me please. i need this program

**Comment by mclarekin** [comment]
The usual problem with win10 is user not changing the timeout in the registry before using openCL.
 But your error is new to me,
 we will need buddhi's advice.

**Comment by buddhi1980** [comment]
Does this problem still happen with new version? Try with 2.18-dev which can be downloaded from here: https://ci.appveyor.com/project/buddhi1980/mandelbulber2/build/job/9iri01xk3b4fqi6c/artifacts

**Comment by ableeker** [comment]
I've discovered mandelbulber2 today, and installed the latest version 2.18-1. It starts and shows the interface, but then crashes after about 5 seconds. It seems to be related to OpenCL. I've gone back to earlier versions, and I've found out that the latest version that will run is 2.12 alpha 7. I've also installed the latest version of 2.19 compiled today, but it displays an error about OpenCL, and then still crashes.
My PC has Windows 10, and an AMD Vega 64.
I've enclosed the error messages I could gather.

[mandelbulber_log_2.12.txt](https://github.com/buddhi1980/mandelbulber2/files/3364868/mandelbulber_log_2.12.txt)
[mandelbulber_log_2.19.txt](https://github.com/buddhi1980/mandelbulber2/files/3364869/mandelbulber_log_2.19.txt)
![ManderError4](https://user-images.githubusercontent.com/2095835/60759156-4d6e9080-a020-11e9-8504-4e3b0267ca85.png)
![ManderError](https://user-images.githubusercontent.com/2095835/60759158-62e3ba80-a020-11e9-9d82-994e08241028.png)

**Comment by buddhi1980** [comment]
Try to delete all *.ini files (mandelbulber_218.ini, mandelbulber_219.ini, ...) from C:/Users/username/mandelbulber/
Let me know if program will start working. OpenCL is disabled by default so it should allow to open preferences window. I see log file from version 2.12. Maybe you have some very old incompatible settings for OpenCL in INI file.

**Comment by mancoast** [comment]
@buddhi1980 Is it possible for the system to detect and auto-recover in scenarios like this one? I do not fully understand what is happening in this case, but I am curious if we can make the initialization of GPU more adaptable to auto-recover if failed ~2 times in a row. Maybe if failed for third time, then automatically offer a new dialog popup window to the user to delete all those *.ini files (mandelbulber_218.ini, mandelbulber_219.ini, ...) from C:/Users/username/mandelbulber/  ?

**Comment by buddhi1980** [comment]
It could be a good idea to have auto-recover option. But first I need to know if deleting INI files will help.

**Comment by ableeker** [comment]
First of all, deleting the INI files doesn't work, 2,18, anything after 2.12 alpha 7 actually, still crashes after 5 seconds or so. I'm not doing anything at this point.
If I start 2.12 alpha 7 first, I can configure this version of mandelbulber, so it carries over to 2.18. I can see in 2.12a7 that OpenCL isn't activated. If I activate it in 2.12a7, and if I act quickly, I can just about reach the OpenCL tab in 2.18 before it crashes.
I've just deleted the INI files, the entire folder mandelbulber actually. I've started 2.17a7, and there's a new IN, with the following content:
# Mandelbulber settings file
# version 2.12
# application settings
[main_parameters]
language ;
logging_verbosity 3;
opencl_platform -1;
I've started 2.18 again, and there's a new INI mandelbulber_218.ini.
# Mandelbulber settings file
# version 2.12
# application settings
[main_parameters]
language ;
logging_verbosity 3;
opencl_platform -1;
Now there's also a new mandelbulber_log file.
Finally, I've deleted the INI files, the entire mandelbulber folder actually, and the log file. This way I'm starting 2.18 with a clean configuration, and OpenCL deactivated, but it's unfortunately still crashing.
![ManderError7](https://user-images.githubusercontent.com/2095835/60766710-19da4780-a0ae-11e9-960b-fe7b303fb3db.png)
[mandelbulber_log.zip](https://github.com/buddhi1980/mandelbulber2/files/3365461/mandelbulber_log.zip)
![ManderError5](https://user-images.githubusercontent.com/2095835/60766516-3fb21d00-a0ab-11e9-93fc-f68c09c2a6d8.png)

**Comment by buddhi1980** [comment]
Does it crash also when OpenCL is disabled?
When exactly it crash? When you click OK in preferences window? When you press RENDER?

**Comment by buddhi1980** [comment]
I see that in your INI file there is '``opencl_platform -1;``` It can cause the problem.
I have just found way how it can be -1. If at first start you will not enable OpenCL and open preferences dialog, then press OK. Close application. Launch again and open preferences again and enable OpenCL. Then no OpenCL platforms are selected. If you press OK again and try to render the program will crash (will try to use platform -1).

**Comment by buddhi1980** [comment]
The problem is probably fixed now. You can try again when new Appveyor build will be available. I will provide link for you soon.

**Comment by buddhi1980** [comment]
Try this build for Windows: https://ci.appveyor.com/project/buddhi1980/mandelbulber2/build/job/p74efras6edl3bws/artifacts
and let me know if it works

**Comment by ableeker** [comment]
Thanks for the build! I've deleted folder mandelbulber, and the log file, and started this build. No INI files, so I'm assuming OpenCL wasn't enabled. Unfortunately it still crashes. It draws the interface, and the icons at the top. The panel in the middle is black. Is it supposed to start rendering at that point? Even if I don't do anything at all, it crashes after about 5 seconds. Now there's no INI at all.
What would be the content of a good INI? Enabling OpenCL in 2.12a7 generates this INI:
# Mandelbulber settings file
# version 2.12
# application settings
[main_parameters]
language ;
opencl_device_list 94ddc2;
opencl_enabled true;
But then 2.19 displays this error:
Error. No OpenCL devices selected or selected unknown devices!
Selected first available GPU device
Check program preferences to select correct OpenCL devicefrom list of available
GPU devices
If I click OK, it crashes after all.

**Comment by buddhi1980** [comment]
First of all stop using 2.12 when we do debugging. It makes a lot of mess. INI file from 2.12 is not fully compatible with 2.19. 2.19 support multiGPU rendering and OpenCL settings are a little different. Even if you select GPU in 2.12 it will not work in 2.19 (will be reported that wrong GPU is selected)
But I think in your case it is not a problem with OpenCL but with something completely different. If you say that it fail after about 5 seconds it means that it crash just after toolbar on the top is fully displayed. The program goes to main event loop. It is very strange that it crashes. There are thousands of uses which runs this program without any issues. It must be something related to your system (some untipical configuration) which makes program unstable. However I would like to know what generates this problem.

To make it easier for me, please do one more test:
- delete content of mandelbulber folder, to not have any INI files and any other auto-generated files
- create new mandelbulber_219.ini file with following content:
```
# Mandelbulber settings file
# version 2.19
# application settings
[main_parameters]
language en_EN;
logging_verbosity 3;
```

- start the newest build
- do nothing and wait until program will crash
- send me log file

**Comment by ableeker** [comment]
The only content was this mandelbulber_219.ini. Started Mandelbulber 2.19. Did nothing. It crashed, and the result was the enclosed mandelbulber_log.txt.
[mandelbulber_log.zip](https://github.com/buddhi1980/mandelbulber2/files/3366094/mandelbulber_log.zip)

**Comment by buddhi1980** [comment]
It is more strange case as it could be. From reading logfile I see that program finishes all action and crashes when there is nothing more to do. I cannot reproduce this problem at all. What I only know that the problem is not related to OpenCL or some specific settings in INI file.
There one more place where Mandelbulber stores something. In Windows registry there is saved windows geometry and state.
![image](https://user-images.githubusercontent.com/11696990/60830755-3793d380-a1b8-11e9-8a06-39007ed5d8bf.png)
Try to delete Computer\HKEY_CURRENT_USER\Software\Mandelbulber folder using regedit.exe and then try to launch program one again.
Additional questions:
- what antivirus software do you use? Have you tried to disable antivirus and run the program?
- what CPU do you have? The problem can be related to CPU type and compiler settings used during compilation.

**Comment by ableeker** [comment]
I've deleted the Registry entry, and disabled the antivirus program. It still crashes.
My computer runs Windows 10 1903 at 1920x1080, and has an i5 4460 CPU, 16 GB RAM, and an Asus RoG Strix RX Vega 64 (gfx900) running Adrenalin 19.7.1.

**Comment by buddhi1980** [comment]
I still don't have idea what could be wrong. I have updated my Windows 10 to version 1903 and still works properly. You have typical CPU, so it shouldn't be a problem. I'm really sorry that I cannot help you now.
